### ISSUE TITLE
PLEASE HELP !!! setPage or setPageWithoutAnimation is not working.

### ISSUE THREAD

**Issue by SaidulBadhon** [callstack/react-native-viewpager#272]
## Ask your Question
HI, im unable to use setPage to set a selected page from a button press. 
I want to go from page 1 to page 5 with a button press.
Can anyone please tell me how can I do it?

**Comment by a-tanyeres** [comment]
How are you using it?

like this?
`myPager.current?.setPage(page);`

**Comment by troZee** [comment]
StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

answer is here:
https://github.com/callstack/react-native-viewpager/blob/master/example/src/BasicViewPagerExample.tsx
