### ISSUE TITLE
Transition duration

### ISSUE THREAD

**Issue by Bardiamist** [callstack/react-native-viewpager#304]
Is possible to remove transition duration?

Because [react-native-tab-view](https://github.com/satya164/react-native-tab-view) now using react-native-viewpager and many people want to switch between tabs immediately.

**Comment by troZee** [comment]
StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-viewpager/blob/master/example/src/hook/useNavigationPanel.ts#L46
