### ISSUE TITLE
App crash after slide of 10 pages

### ISSUE THREAD

**Issue by IsmetGlumcevic** [callstack/react-native-viewpager#49]
RN 0.60 

I have 600 pages. This is code. After fast lsiding of 10 pages app crash.
Doas viewager has RTL support?

       <ViewPager
             style={{flex:1}}
              initialPage={5}>
              {dataar.map((item, index) => {
                    return(
                        <View key={index + 1}>
                          {Object.values(item)[0].map((it, key) => {
                              return key == 0 ?
                                    <TouchableOpacity key={key} activeOpacity={1} style= . 
       {styles.imageView} onPress={this.showHeaderFooter}>
                                           <Image style={{ width: IMGWIDTH, height: IMGHEIGHT }} 
        source={it.url} />
                                      </TouchableOpacity>
                                 : null
                                })
                              }
                        </View>
                        )
                      })
                   }
     </ViewPager>

**Comment by ptrocki** [comment]
This component renders all children immediately, so in above case app will crash. We need to figure out, how to handle this case.

**Comment by IsmetGlumcevic** [comment]
I reduced it to 30 items and again app crash.

**Comment by ferrannp** [comment]
@IsmetGlumcevic you should probably add few pages and then add them dynamically while you move between them. Could you also share a repository where we can reproduce it?

**Comment by Kasemyassine2** [comment]
@ferrannp  this scenario happened with us with low memory phones after logging it on android studio it showed this error that it's out of memory after 100 scroll.

As for rtl I just did the a replica with the following function edited in ReactViewPage.java

/*package*/ void addViewToAdapter(View child, int index) {
    getAdapter().addView(child, 0);
  }

so instead of adding at the end of the list I've added at index 0 with no performance issues!
